### ISSUE TITLE
Amazing work - just some clarifications 

### ISSUE THREAD

**Issue by TontonTremblay** [3dlg-hcvc/paris#1]
Hello, amazing work, I love the simplicity of the method and I quite like the setting. 

In the paper you mention that the "If it is not given, we first optimize the transformation as a SE(3) group to classify the motion type as a pre-processing step". Do you have more information about this process? 

Do you have numbers about how long the current codebase needs to optimize for an object? I could not find that information in the paper either. 

Thank you in advance, and again congrats on this amazing work.

**Comment by SevenLJY** [comment]
Greetings! Really appreciate your interest in our work!

Conceptually, this "SE(3) preprocessing step" is a variant of our training/optimization pipeline, which exchanges the transformation params with an SE(3) group, represented as a unit quaternion and a translation vector. Other parts of the pipeline remain the same. Once the optimization is finished, we can classify the joint as prismatic if the rotation angle is close to zero, otherwise, it is classified as a revolute joint. 

Practically, we provide the implementation of this process by training the model with `--config configs/se3.yaml` within 5k steps. On a single RTX 3060 GPU, it will take roughly 5 mins. 

For the complete optimization (pure revolute or prismatic), the experiment results shown in the paper are trained in 30k steps for each object, which takes around 30 mins on a single RTX 3060. (The model usually converges around 10k, and later steps are mostly refining the details.)

Hope this helps clarification. Some of those details are actually in the supplementals, but not presented in the arxiv version (might included later). Thank you for your questions!

Regards,
Jiayi

**Comment by TontonTremblay** [comment]
Thank you for the prompt answer, firstly we need to get you a better GPU ;) I am impressed this all run on a single 3060. The optimization for the joint makes more sense now, thank you. I figured most of my questions had answers in a supp. material, since I was not a reviewer I had no way to find out. I look forward possibly looking into the supp. materials.
