### ISSUE TITLE
scale between start and final

### ISSUE THREAD

**Issue by Guptajakala** [3dlg-hcvc/paris#2]
Hi, very cool work! 

It's said only RGB is needed. How are the scales ensured to be consistent between the scans for the start and end states?

**Comment by SevenLJY** [comment]
Hi! Thanks for your interest in our work!

As you might notice, it is an assumption in our problem setting that the objects in the start and end states have been aligned in the world coordinate system. 
For the experiments shown in the paper, the scale consistency comes with the datasets. 
In a real scanning setting, this can be ensured by sharing at least one input view across two states. That being said, as long as the camera is fixed in the sharing view and the object is fixed (and only articulating the part), then the scale is consistent.

Hope it helps!
